Repository colaboradados/colaboradados.github.io, pull requests merged in 2019-10, with the labels that each got.

#106 Add Janaúba-MG
  _states/minas-gerais.md
Labels: enhancement

#109 Adicionei Januária e Diamantina
  _states/minas-gerais.md
Labels: enhancement

#107 add Japonvar
  _states/minas-gerais.md
Labels: enhancement

#110 add riacho dos machados
  _states/minas-gerais.md
Labels: enhancement

#112 Adicionei algumas cidades do ES
  _states/espirito-santo.md
Labels: enhancement

#121 Documenta a instalação do projeto para Mac
  README.md
Labels: enhancement, solved issue

#123 Adicionando cidades do RN
  _states/rio-grande-do-norte.md
Labels: enhancement

#122 Coloca registros em ordem alfabética
  _posts/2019-01-11-seguranca-publica.md
  _posts/2019-01-12-colecoes.md
  _posts/2019-01-13-ibge.md
  _posts/2019-01-14-paises.md
  _posts/2019-01-15-educacao.md
  _posts/2019-01-16-saude.md
  _posts/2019-01-17-musica.md
  _posts/2019-01-18-cinema.md
  _posts/2019-01-20-esfera-estadual.md
  _posts/2019-01-21-esfera-federal.md
  _states/acre.md
  _states/alagoas.md
  _states/amapa.md
  _states/amazonas.md
  _states/bahia.md
  _states/ceara.md
  _states/espirito-santo.md
  _states/goias.md
  _states/maranhao.md
  _states/mato-grosso-do-sul.md
  _states/mato-grosso.md
  _states/minas-gerais.md
  _states/para.md
  _states/paraiba.md
  _states/parana.md
  _states/pernambuco.md
  _states/piaui.md
  _states/rio-de-janeiro.md
  _states/rio-grande-do-norte.md
  _states/rio-grande-do-sul.md
  _states/rondonia.md
  _states/roraima.md
  _states/santa-catarina.md
  _states/sao-paulo.md
  _states/sergipe.md
  _states/tocantins.md
Labels: enhancement, solved issue

#117 Feat/readme index
  README.md
Labels: docs, enhancement

#111 ADD Cáceres
  _states/mato-grosso.md
Labels: enhancement

#108 Adicionando Serranópolis de Minas
  _states/goias.md
  _states/minas-gerais.md
Labels: enhancement

#141 Update 2019-01-17-musica.md
  _posts/2019-01-17-musica.md
Labels: enhancement

#151 add newsletter edicao 7
  _newsletter/edicao-7.md
Labels: enhancement

#113 Added some cities from RN
  _states/rio-grande-do-norte.md
Labels: enhancement

#160 feat: inclusão de fotos Lucas e Neto
  images/lucashiago.png
  images/netochaves.png
Labels: enhancement
